In [1]:
import pandas as pd
import numpy as np

In [2]:
%ls datasets/

adult.csv                  census.csv     movies.csv
airline_data.csv           coches.csv     nhanes_2015_2016.csv
antropometria00.csv        cwurData.csv   pokemon.csv
antropometria-dataset.csv  data.csv       reg_data.csv
Book3.csv                  headbrain.csv  sample_pivot.csv
Canada.xlsx                mic2.xlsx      tips.csv
Cartwheeldata.csv          mic.xlsx       weight-height.csv

In [3]:
df= pd.read_csv("datasets/census.csv")
df.head(2)

,SUMLEV,REGION,DIVISION,STATE,COUNTY,STNAME,CTYNAME,CENSUS2010POP,ESTIMATESBASE2010,POPESTIMATE2010,...,RDOMESTICMIG2011,RDOMESTICMIG2012,RDOMESTICMIG2013,RDOMESTICMIG2014,RDOMESTICMIG2015,RNETMIG2011,RNETMIG2012,RNETMIG2013,RNETMIG2014,RNETMIG2015
0,40,3,6,1,0,Alabama,Alabama,4779736,4780127,4785161,...,0.002295,-0.193196,0.381066,0.582002,-0.467369,1.030015,0.826644,1.383282,1.724718,0.712594
1,50,3,6,1,1,Alabama,Autauga County,54571,54571,54660,...,7.242091,-2.915927,-3.012349,2.265971,-2.530799,7.606016,-2.626146,-2.722002,2.592270,-2.187333

In [4]:
df.describe()

,SUMLEV,REGION,DIVISION,STATE,COUNTY,CENSUS2010POP,ESTIMATESBASE2010,POPESTIMATE2010,POPESTIMATE2011,POPESTIMATE2012,...,RDOMESTICMIG2011,RDOMESTICMIG2012,RDOMESTICMIG2013,RDOMESTICMIG2014,RDOMESTICMIG2015,RNETMIG2011,RNETMIG2012,RNETMIG2013,RNETMIG2014,RNETMIG2015
count,3193.000000,3193.000000,3193.000000,3193.000000,3193.000000,3.193000e+03,3.193000e+03,3.193000e+03,3.193000e+03,3.193000e+03,...,3193.000000,3193.000000,3193.000000,3193.000000,3193.000000,3193.000000,3193.000000,3193.000000,3193.000000,3193.000000
mean,49.840276,2.668650,5.191356,30.259004,101.918572,1.933871e+05,1.933969e+05,1.937657e+05,1.952514e+05,1.967445e+05,...,-1.639167,-2.528381,-1.288083,-2.271925,-1.362607,-0.655205,-1.445775,-0.200419,-1.038960,-0.096759
std,1.253884,0.807513,1.973991,15.153897,107.626583,1.176201e+06,1.176244e+06,1.178710e+06,1.189648e+06,1.200508e+06,...,10.407267,11.871798,12.186844,11.440505,12.301558,10.613259,12.228155,12.200064,11.471743,12.265772
min,40.000000,1.000000,1.000000,1.000000,0.000000,8.200000e+01,8.200000e+01,8.300000e+01,9.000000e+01,8.100000e+01,...,-128.205128,-147.727273,-109.876862,-178.947368,-84.844838,-128.205128,-147.727273,-102.988031,-178.947368,-62.322703
25%,50.000000,2.000000,4.000000,18.000000,33.000000,1.129900e+04,1.129900e+04,1.127500e+04,1.127700e+04,1.119500e+04,...,-6.153101,-7.561799,-6.323058,-7.357497,-6.696825,-5.354221,-6.851764,-5.426357,-6.221820,-5.553088
50%,50.000000,3.000000,5.000000,29.000000,77.000000,2.642400e+04,2.644600e+04,2.646700e+04,2.641700e+04,2.636200e+04,...,-1.544618,-2.549859,-1.771445,-1.988101,-2.026566,-0.626174,-1.537988,-0.788296,-0.911948,-0.872527
75%,50.000000,3.000000,7.000000,45.000000,133.000000,7.140400e+04,7.149100e+04,7.172100e+04,7.238700e+04,7.249600e+04,...,2.901204,2.626611,3.392786,3.333927,3.794291,4.062151,3.962629,4.700873,4.580444,5.013928
max,50.000000,4.000000,9.000000,56.000000,840.000000,3.725396e+07,3.725450e+07,3.733408e+07,3.770003e+07,3.805606e+07,...,101.123596,119.193807,239.130435,146.367943,281.407035,101.123596,119.861185,239.130435,146.960126,281.407035

In [10]:
x = df.columns.tolist()
x.sort()
x

['BIRTHS2010',
 'BIRTHS2011',
 'BIRTHS2012',
 'BIRTHS2013',
 'BIRTHS2014',
 'BIRTHS2015',
 'CENSUS2010POP',
 'COUNTY',
 'CTYNAME',
 'DEATHS2010',
 'DEATHS2011',
 'DEATHS2012',
 'DEATHS2013',
 'DEATHS2014',
 'DEATHS2015',
 'DIVISION',
 'DOMESTICMIG2010',
 'DOMESTICMIG2011',
 'DOMESTICMIG2012',
 'DOMESTICMIG2013',
 'DOMESTICMIG2014',
 'DOMESTICMIG2015',
 'ESTIMATESBASE2010',
 'GQESTIMATES2010',
 'GQESTIMATES2011',
 'GQESTIMATES2012',
 'GQESTIMATES2013',
 'GQESTIMATES2014',
 'GQESTIMATES2015',
 'GQESTIMATESBASE2010',
 'INTERNATIONALMIG2010',
 'INTERNATIONALMIG2011',
 'INTERNATIONALMIG2012',
 'INTERNATIONALMIG2013',
 'INTERNATIONALMIG2014',
 'INTERNATIONALMIG2015',
 'NATURALINC2010',
 'NATURALINC2011',
 'NATURALINC2012',
 'NATURALINC2013',
 'NATURALINC2014',
 'NATURALINC2015',
 'NETMIG2010',
 'NETMIG2011',
 'NETMIG2012',
 'NETMIG2013',
 'NETMIG2014',
 'NETMIG2015',
 'NPOPCHG_2010',
 'NPOPCHG_2011',
 'NPOPCHG_2012',
 'NPOPCHG_2013',
 'NPOPCHG_2014',
 'NPOPCHG_2015',
 'POPESTIMATE2010',
 'POPESTIMATE2011',
 'POPESTIMATE2012',
 'POPESTIMATE2013',
 'POPESTIMATE2014',
 'POPESTIMATE2015',
 'RBIRTH2011',
 'RBIRTH2012',
 'RBIRTH2013',
 'RBIRTH2014',
 'RBIRTH2015',
 'RDEATH2011',
 'RDEATH2012',
 'RDEATH2013',
 'RDEATH2014',
 'RDEATH2015',
 'RDOMESTICMIG2011',
 'RDOMESTICMIG2012',
 'RDOMESTICMIG2013',
 'RDOMESTICMIG2014',
 'RDOMESTICMIG2015',
 'REGION',
 'RESIDUAL2010',
 'RESIDUAL2011',
 'RESIDUAL2012',
 'RESIDUAL2013',
 'RESIDUAL2014',
 'RESIDUAL2015',
 'RINTERNATIONALMIG2011',
 'RINTERNATIONALMIG2012',
 'RINTERNATIONALMIG2013',
 'RINTERNATIONALMIG2014',
 'RINTERNATIONALMIG2015',
 'RNATURALINC2011',
 'RNATURALINC2012',
 'RNATURALINC2013',
 'RNATURALINC2014',
 'RNATURALINC2015',
 'RNETMIG2011',
 'RNETMIG2012',
 'RNETMIG2013',
 'RNETMIG2014',
 'RNETMIG2015',
 'STATE',
 'STNAME',
 'SUMLEV']

In [12]:
pd.pivot_table(df,
               index = 'STNAME',
               aggfunc = ['median','mean'],
               values = ['BIRTHS2010', 'BIRTHS2011'],
               margins = True,
               columns = 'SUMLEV'
              )

                         median                                             \
                     BIRTHS2010                 BIRTHS2011
SUMLEV                       40      50     All         40      50     All
STNAME
Alabama                 14226.0   102.0   111.0    59689.0   419.0   441.0
Alaska                   2892.0    22.0    24.5    11711.0   117.0   119.5
Arizona                 20937.0   428.0   440.5    86104.0  1773.0  1787.5
Arkansas                 9439.0    53.0    54.5    38445.0   234.0   238.0
California             123324.0   571.5   574.0   509767.0  2431.5  2440.0
Colorado                16791.0    37.5    38.0    65916.0   148.5   149.0
Connecticut              9489.0   537.0   656.0    37636.0  2159.5  2763.0
Delaware                 2847.0   572.0  1139.0    11299.0  2234.0  4551.5
District of Columbia     2243.0  2243.0  2243.0     9196.0  9196.0  9196.0
Florida                 50872.0   226.0   235.0   213217.0   913.0   955.0
Georgia                 32489.0    63.0    64.5   132615.0   271.0   272.5
Hawaii                   4646.0   479.0   535.0    19153.0  2033.0  2244.0
Idaho                    5971.0    44.5    48.0    22955.0   171.5   177.0
Illinois                41836.0    68.5    69.0   162427.0   302.0   304.0
Indiana                 20961.0   105.5   106.0    83457.0   395.5   400.0
Iowa                     9967.0    47.0    47.0    37856.0   160.0   160.0
Kansas                   9992.0    21.0    21.0    40118.0    90.0    90.0
Kentucky                13691.0    55.0    56.0    55313.0   219.0   219.0
Louisiana               14573.0   101.0   102.0    62316.0   441.0   458.0
Maine                    3443.0   128.5   132.0    12631.0   473.0   493.0
Maryland                18461.0   345.5   364.0    73541.0  1382.0  1482.0
Massachusetts           18647.0  1311.5  1328.0    73185.0  5357.0  5535.0
Michigan                29102.0   109.0   109.5   113984.0   411.0   425.0
Minnesota               17500.0    66.0    68.5    68372.0   263.0   270.0
Mississippi              9421.0    76.5    77.0    39741.0   323.0   328.0
Missouri                19012.0    51.0    52.5    76238.0   228.0   230.0
Montana                  3068.0    17.5    18.0    11999.0    75.0    78.0
Nebraska                 6515.0    19.0    19.5    25730.0    70.0    71.0
Nevada                   8892.0    60.0    65.5    35847.0   265.0   286.0
New Hampshire            3269.0   183.5   186.0    12993.0   751.5   760.0
New Jersey              26529.0  1187.0  1227.0   106684.0  4670.0  4745.0
New Mexico               6649.0    84.0    88.0    27803.0   320.0   329.0
New York                61414.0   248.0   248.0   243118.0   921.0   934.0
North Carolina          29914.0   145.0   147.0   121043.0   607.5   608.0
North Dakota             2341.0    10.0    10.0     9197.0    41.0    41.0
Ohio                    34809.0   162.0   163.0   137935.0   609.5   615.0
Oklahoma                13144.0    65.0    68.5    52555.0   286.0   291.0
Oregon                  11877.0   122.0   126.0    45395.0   438.0   441.0
Pennsylvania            36101.0   225.0   231.0   142957.0   861.0   889.0
Rhode Island             2875.0   238.0   322.5    11004.0   952.0  1271.5
South Carolina          14180.0   159.5   184.0    57472.0   638.5   691.0
South Dakota             3032.0    17.0    17.0    11787.0    68.5    69.0
Tennessee               19663.0    81.0    87.0    78616.0   336.0   341.5
Texas                   92767.0    53.0    53.0   381746.0   219.0   221.0
Utah                    13752.0    79.0    83.5    51915.0   346.0   358.5
Vermont                  1654.0    95.0   101.0     6052.0   318.5   323.0
Virginia                25718.0    68.0    68.0   102327.0   257.0   260.5
Washington              22244.0   161.0   164.0    86703.0   685.0   685.0
West Virginia            5104.0    64.0    64.5    20462.0   271.0   274.0
Wisconsin               17558.0   116.5   120.0    67792.0   416.5   432.0
Wyoming                  1995.0    57.0    65.0     7471.0   200.0   220.5
All                     13752.0    76.0    78.0    55313.0   304.0   311.0

                               mean                                           \
                         BIRTHS2010                               BIRTHS2011
SUMLEV                           40           50          All             40
STNAME
Alabama                14226.000000   212.328358   418.411765   59689.000000
Alaska                  2892.000000    99.724138   192.800000   11711.000000
Arizona                20937.000000  1395.800000  2617.125000   86104.000000
Arkansas                9439.000000   125.853333   248.394737   38445.000000
California            123324.000000  2126.275862  4180.474576  509767.000000
Colorado               16791.000000   262.359375   516.646154   65916.000000
Connecticut             9489.000000  1186.125000  2108.666667   37636.000000
Delaware                2847.000000   949.000000  1423.500000   11299.000000
District of Columbia    2243.000000  2243.000000  2243.000000    9196.000000
Florida                50872.000000   759.283582  1496.235294  213217.000000
Georgia                32489.000000   204.333333   406.112500  132615.000000
Hawaii                  4646.000000   929.200000  1548.666667   19153.000000
Idaho                   5971.000000   135.704545   265.377778   22955.000000
Illinois               41836.000000   410.156863   812.349515  162427.000000
Indiana                20961.000000   227.836957   450.774194   83457.000000
Iowa                    9967.000000   100.676768   199.340000   37856.000000
Kansas                  9992.000000    95.161905   188.528302   40118.000000
Kentucky               13691.000000   114.091667   226.297521   55313.000000
Louisiana              14573.000000   227.703125   448.400000   62316.000000
Maine                   3443.000000   215.187500   405.058824   12631.000000
Maryland               18461.000000   769.208333  1476.880000   73541.000000
Massachusetts          18647.000000  1331.928571  2486.266667   73185.000000
Michigan               29102.000000   350.626506   692.904762  113984.000000
Minnesota              17500.000000   201.149425   397.727273   68372.000000
Mississippi             9421.000000   114.890244   227.012048   39741.000000
Missouri               19012.000000   165.321739   327.793103   76238.000000
Montana                 3068.000000    54.785714   107.649123   11999.000000
Nebraska                6515.000000    70.053763   138.617021   25730.000000
Nevada                  8892.000000   523.058824   988.000000   35847.000000
New Hampshire           3269.000000   326.900000   594.363636   12993.000000
New Jersey             26529.000000  1263.285714  2411.727273  106684.000000
New Mexico              6649.000000   201.484848   391.117647   27803.000000
New York               61414.000000   990.548387  1949.650794  243118.000000
North Carolina         29914.000000   299.140000   592.356436  121043.000000
North Dakota            2341.000000    44.169811    86.703704    9197.000000
Ohio                   34809.000000   395.556818   782.224719  137935.000000
Oklahoma               13144.000000   170.701299   337.025641   52555.000000
Oregon                 11877.000000   329.916667   642.000000   45395.000000
Pennsylvania           36101.000000   538.820896  1061.794118  142957.000000
Rhode Island            2875.000000   575.000000   958.333333   11004.000000
South Carolina         14180.000000   308.260870   603.404255   57472.000000
South Dakota            3032.000000    45.939394    90.507463   11787.000000
Tennessee              19663.000000   206.978947   409.645833   78616.000000
Texas                  92767.000000   365.224409   727.584314  381746.000000
Utah                   13752.000000   474.206897   916.800000   51915.000000
Vermont                 1654.000000   118.142857   220.533333    6052.000000
Virginia               25718.000000   193.368421   383.850746  102327.000000
Washington             22244.000000   570.358974  1112.200000   86703.000000
West Virginia           5104.000000    92.800000   182.285714   20462.000000
Wisconsin              17558.000000   243.861111   481.041096   67792.000000
Wyoming                 1995.000000    86.739130   166.250000    7471.000000
All                    19369.333333   314.397199   618.751018   77911.470588



SUMLEV                         50           All
STNAME
Alabama                890.880597   1755.558824
Alaska                 403.827586    780.733333
Arizona               5740.266667  10763.000000
Arkansas               512.600000   1011.710526
California            8789.086207  17280.237288
Colorado              1029.937500   2028.184615
Connecticut           4704.500000   8363.555556
Delaware              3766.333333   5649.500000
District of Columbia  9196.000000   9196.000000
Florida               3182.343284   6271.088235
Georgia                834.056604   1657.687500
Hawaii                3830.600000   6384.333333
Idaho                  521.704545   1020.222222
Illinois              1592.421569   3153.922330
Indiana                907.141304   1794.774194
Iowa                   382.383838    757.120000
Kansas                 382.076190    756.943396
Kentucky               460.941667    914.264463
Louisiana              973.687500   1917.415385
Maine                  789.437500   1486.000000
Maryland              3064.208333   5883.280000
Massachusetts         5227.500000   9758.000000
Michigan              1373.301205   2713.904762
Minnesota              785.885057   1553.909091
Mississippi            484.646341    957.614458
Missouri               662.939130   1314.448276
Montana                214.267857    421.017544
Nebraska               276.666667    547.446809
Nevada                2108.647059   3983.000000
New Hampshire         1299.300000   2362.363636
New Jersey            5080.190476   9698.545455
New Mexico             842.515152   1635.470588
New York              3921.258065   7718.031746
North Carolina        1210.430000   2396.891089
North Dakota           173.528302    340.629630
Ohio                  1567.443182   3099.662921
Oklahoma               682.532468   1347.564103
Oregon                1260.972222   2453.783784
Pennsylvania          2133.686567   4204.617647
Rhode Island          2200.800000   3668.000000
South Carolina        1249.391304   2445.617021
South Dakota           178.590909    351.850746
Tennessee              827.536842   1637.833333
Texas                 1502.937008   2994.086275
Utah                  1790.172414   3461.000000
Vermont                432.285714    806.933333
Virginia               769.375940   1527.268657
Washington            2223.153846   4335.150000
West Virginia          372.036364    730.785714
Wisconsin              941.555556   1857.315068
Wyoming                324.826087    622.583333
All                   1264.635582   2488.872534

In [13]:
df['BIRTHS2010'].describe()

count      3193.000000
mean        618.751018
std        3838.926925
min           0.000000
25%          31.000000
50%          78.000000
75%         216.000000
max      123324.000000
Name: BIRTHS2010, dtype: float64

In [14]:
%ls datasets/

adult.csv                  census.csv     movies.csv
airline_data.csv           coches.csv     nhanes_2015_2016.csv
antropometria00.csv        cwurData.csv   pokemon.csv
antropometria-dataset.csv  data.csv       reg_data.csv
Book3.csv                  headbrain.csv  sample_pivot.csv
Canada.xlsx                mic2.xlsx      tips.csv
Cartwheeldata.csv          mic.xlsx       weight-height.csv

In [16]:
adf = pd.read_csv('datasets/airline_data.csv', low_memory=False)

In [19]:
x = adf.columns.tolist()
x.sort()
x

['ActualElapsedTime',
 'AirTime',
 'ArrDel15',
 'ArrDelay',
 'ArrDelayMinutes',
 'ArrTime',
 'ArrTimeBlk',
 'ArrivalDelayGroups',
 'CRSArrTime',
 'CRSDepTime',
 'CRSElapsedTime',
 'CancellationCode',
 'Cancelled',
 'CarrierDelay',
 'DOT_ID_Reporting_Airline',
 'DayOfWeek',
 'DayofMonth',
 'DepDel15',
 'DepDelay',
 'DepDelayMinutes',
 'DepTime',
 'DepTimeBlk',
 'DepartureDelayGroups',
 'Dest',
 'DestAirportID',
 'DestAirportSeqID',
 'DestCityMarketID',
 'DestCityName',
 'DestState',
 'DestStateFips',
 'DestStateName',
 'DestWac',
 'Distance',
 'DistanceGroup',
 'Div1Airport',
 'Div1AirportID',
 'Div1AirportSeqID',
 'Div1LongestGTime',
 'Div1TailNum',
 'Div1TotalGTime',
 'Div1WheelsOff',
 'Div1WheelsOn',
 'Div2Airport',
 'Div2AirportID',
 'Div2AirportSeqID',
 'Div2LongestGTime',
 'Div2TailNum',
 'Div2TotalGTime',
 'Div2WheelsOff',
 'Div2WheelsOn',
 'Div3Airport',
 'Div3AirportID',
 'Div3AirportSeqID',
 'Div3LongestGTime',
 'Div3TailNum',
 'Div3TotalGTime',
 'Div3WheelsOff',
 'Div3WheelsOn',
 'Div4Airport',
 'Div4AirportID',
 'Div4AirportSeqID',
 'Div4LongestGTime',
 'Div4TailNum',
 'Div4TotalGTime',
 'Div4WheelsOff',
 'Div4WheelsOn',
 'Div5Airport',
 'Div5AirportID',
 'Div5AirportSeqID',
 'Div5LongestGTime',
 'Div5TailNum',
 'Div5TotalGTime',
 'Div5WheelsOff',
 'Div5WheelsOn',
 'DivActualElapsedTime',
 'DivAirportLandings',
 'DivArrDelay',
 'DivDistance',
 'DivReachedDest',
 'Diverted',
 'FirstDepTime',
 'FlightDate',
 'Flight_Number_Reporting_Airline',
 'Flights',
 'IATA_CODE_Reporting_Airline',
 'LateAircraftDelay',
 'LongestAddGTime',
 'Month',
 'NASDelay',
 'Origin',
 'OriginAirportID',
 'OriginAirportSeqID',
 'OriginCityMarketID',
 'OriginCityName',
 'OriginState',
 'OriginStateFips',
 'OriginStateName',
 'OriginWac',
 'Quarter',
 'Reporting_Airline',
 'SecurityDelay',
 'Tail_Number',
 'TaxiIn',
 'TaxiOut',
 'TotalAddGTime',
 'Unnamed: 0',
 'WeatherDelay',
 'WheelsOff',
 'WheelsOn',
 'Year']

## 1. What is the minimun and maximun delay of airlines?

In [25]:
adf.loc[:,'DepDelay'].max()

988.0

In [31]:
pd.set_option('display.max_rows', 5000)

In [32]:
adf.groupby(['DepDelay', 'DepartureDelayGroups']).size()

DepDelay  DepartureDelayGroups
-23.0     -2.0                       1
-19.0     -2.0                       2
-18.0     -2.0                       1
-17.0     -2.0                       3
-16.0     -2.0                       6
-15.0     -1.0                      12
-14.0     -1.0                      11
-13.0     -1.0                      20
-12.0     -1.0                      20
-11.0     -1.0                      42
-10.0     -1.0                     112
-9.0      -1.0                     131
-8.0      -1.0                     181
-7.0      -1.0                     240
-6.0      -1.0                     350
-5.0      -1.0                     495
-4.0      -1.0                     538
-3.0      -1.0                     601
-2.0      -1.0                     705
-1.0      -1.0                     673
 0.0       0.0                    1468
 1.0       0.0                     324
 2.0       0.0                     264
 3.0       0.0                     222
 4.0       0.0                     189
 5.0       0.0                     181
 6.0       0.0                     133
 7.0       0.0                     119
 8.0       0.0                     126
 9.0       0.0                      94
 10.0      0.0                     104
 11.0      0.0                      79
 12.0      0.0                      76
 13.0      0.0                      72
 14.0      0.0                      68
 15.0      1.0                      69
 16.0      1.0                      59
 17.0      1.0                      51
 18.0      1.0                      48
 19.0      1.0                      51
 20.0      1.0                      62
 21.0      1.0                      43
 22.0      1.0                      52
 23.0      1.0                      32
 24.0      1.0                      22
 25.0      1.0                      40
 26.0      1.0                      33
 27.0      1.0                      30
 28.0      1.0                      37
 29.0      1.0                      26
 30.0      2.0                      36
 31.0      2.0                      17
 32.0      2.0                      18
 33.0      2.0                      29
 34.0      2.0                      22
 35.0      2.0                      28
 36.0      2.0                      23
 37.0      2.0                      17
 38.0      2.0                      15
 39.0      2.0                      16
 40.0      2.0                      27
 41.0      2.0                      15
 42.0      2.0                      15
 43.0      2.0                      26
 44.0      2.0                      23
 45.0      3.0                      22
 46.0      3.0                      10
 47.0      3.0                      11
 48.0      3.0                      11
 49.0      3.0                      15
 50.0      3.0                      14
 51.0      3.0                      11
 52.0      3.0                      17
 53.0      3.0                      12
 54.0      3.0                      15
 55.0      3.0                      15
 56.0      3.0                       9
 57.0      3.0                      12
 58.0      3.0                      12
 59.0      3.0                       9
 60.0      4.0                      15
 61.0      4.0                       8
 62.0      4.0                       9
 63.0      4.0                      11
 64.0      4.0                       9
 65.0      4.0                      11
 66.0      4.0                       8
 67.0      4.0                       7
 68.0      4.0                       9
 69.0      4.0                       8
 70.0      4.0                      14
 71.0      4.0                       6
 72.0      4.0                       7
 73.0      4.0                       6
 74.0      4.0                       8
 75.0      5.0                       7
 76.0      5.0                       2
 77.0      5.0                       6
 78.0      5.0                       8
 79.0      5.0                       4
 80.0      5.0                       6
 81.0      5.0                       6
 82.0      5.0                       3
 83.0      5.0                       7
 84.0      5.0                       6
 85.0      5.0                       6
 86.0      5.0                       6
 87.0      5.0                       7
 88.0      5.0                       3
 89.0      5.0                       3
 90.0      6.0                       7
 91.0      6.0                       3
 93.0      6.0                       2
 94.0      6.0                       2
 95.0      6.0                       7
 96.0      6.0                       2
 97.0      6.0                       5
 98.0      6.0                       7
 99.0      6.0                       6
 100.0     6.0                       3
 101.0     6.0                       1
 102.0     6.0                       1
 103.0     6.0                       6
 104.0     6.0                       4
 106.0     7.0                       2
 107.0     7.0                       3
 108.0     7.0                       4
 109.0     7.0                       2
 110.0     7.0                       5
 111.0     7.0                       3
 112.0     7.0                       1
 113.0     7.0                       5
 114.0     7.0                       4
 115.0     7.0                       1
 116.0     7.0                       3
 117.0     7.0                       4
 118.0     7.0                       2
 119.0     7.0                       3
 120.0     8.0                       2
 121.0     8.0                       5
 122.0     8.0                       1
 123.0     8.0                       2
 124.0     8.0                       4
 125.0     8.0                       2
 126.0     8.0                       1
 128.0     8.0                       2
 129.0     8.0                       1
 130.0     8.0                       1
 131.0     8.0                       1
 132.0     8.0                       2
 133.0     8.0                       1
 134.0     8.0                       1
 137.0     9.0                       1
 138.0     9.0                       2
 139.0     9.0                       1
 140.0     9.0                       4
 141.0     9.0                       2
 143.0     9.0                       2
 144.0     9.0                       2
 145.0     9.0                       1
 146.0     9.0                       2
 147.0     9.0                       1
 149.0     9.0                       3
 150.0     10.0                      5
 151.0     10.0                      1
 153.0     10.0                      1
 155.0     10.0                      3
 156.0     10.0                      2
 157.0     10.0                      1
 158.0     10.0                      4
 159.0     10.0                      1
 160.0     10.0                      2
 161.0     10.0                      1
 162.0     10.0                      2
 164.0     10.0                      1
 165.0     11.0                      2
 168.0     11.0                      2
 170.0     11.0                      2
 171.0     11.0                      2
 172.0     11.0                      2
 174.0     11.0                      1
 177.0     11.0                      2
 179.0     11.0                      1
 180.0     12.0                      3
 181.0     12.0                      1
 183.0     12.0                      1
 184.0     12.0                      1
 185.0     12.0                      1
 187.0     12.0                      1
 189.0     12.0                      2
 191.0     12.0                      1
 193.0     12.0                      1
 196.0     12.0                      1
 197.0     12.0                      1
 198.0     12.0                      1
 199.0     12.0                      1
 205.0     12.0                      1
 207.0     12.0                      1
 208.0     12.0                      1
 214.0     12.0                      1
 220.0     12.0                      1
 221.0     12.0                      1
 223.0     12.0                      1
 224.0     12.0                      2
 233.0     12.0                      1
 238.0     12.0                      1
 241.0     12.0                      1
 248.0     12.0                      1
 263.0     12.0                      1
 267.0     12.0                      2
 282.0     12.0                      1
 289.0     12.0                      1
 308.0     12.0                      1
 330.0     12.0                      1
 339.0     12.0                      1
 346.0     12.0                      1
 365.0     12.0                      1
 376.0     12.0                      1
 400.0     12.0                      1
 403.0     12.0                      1
 460.0     12.0                      1
 600.0     12.0                      1
 732.0     12.0                      1
 988.0     12.0                      1
dtype: int64

In [39]:
pd.pivot_table(adf,
               index = ['Year','Quarter'],
               values = 'DepDelay',
               aggfunc = 'count',
               columns = 'DepartureDelayGroups',
               margins = True,
              )

DepartureDelayGroups  -2.0    -1.0     0.0    1.0    2.0    3.0    4.0   5.0  \
Year Quarter
1987 4                 NaN     7.0    35.0    7.0    1.0    2.0    NaN   NaN
1988 1                 NaN     9.0    42.0    6.0    NaN    2.0    1.0   1.0
     2                 NaN     8.0    41.0    6.0    3.0    1.0    NaN   1.0
     3                 NaN    14.0    49.0    1.0    1.0    NaN    NaN   NaN
     4                 NaN     7.0    46.0    6.0    3.0    NaN    1.0   1.0
1989 1                 NaN    15.0    35.0    7.0    3.0    2.0    2.0   NaN
     2                 NaN    10.0    38.0    5.0    1.0    NaN    NaN   1.0
     3                 NaN    11.0    43.0    4.0    1.0    NaN    3.0   1.0
     4                 NaN     6.0    35.0    4.0    1.0    2.0    NaN   NaN
1990 1                 NaN    16.0    33.0    7.0    NaN    NaN    1.0   NaN
     2                 NaN    21.0    37.0    5.0    NaN    NaN    NaN   NaN
     3                 NaN    17.0    36.0    2.0    NaN    1.0    2.0   NaN
     4                 NaN    13.0    40.0    5.0    3.0    NaN    1.0   NaN
1991 1                 NaN    18.0    24.0    3.0    4.0    1.0    NaN   NaN
     2                 NaN    17.0    40.0    6.0    1.0    NaN    NaN   NaN
     3                 NaN    13.0    58.0    5.0    3.0    3.0    NaN   1.0
     4                 NaN    14.0    37.0    1.0    2.0    NaN    1.0   NaN
1992 1                 NaN    17.0    33.0    2.0    1.0    1.0    NaN   NaN
     2                 NaN    15.0    32.0    3.0    NaN    NaN    NaN   NaN
     3                 NaN    14.0    39.0    2.0    3.0    1.0    NaN   NaN
     4                 NaN    15.0    46.0    8.0    NaN    1.0    NaN   NaN
1993 1                 NaN    14.0    30.0    4.0    3.0    3.0    1.0   NaN
     2                 NaN    24.0    30.0    1.0    2.0    1.0    NaN   NaN
     3                 NaN    22.0    35.0    3.0    1.0    1.0    NaN   NaN
     4                 NaN    20.0    21.0    6.0    1.0    1.0    NaN   NaN
1994 1                 NaN    10.0    36.0    5.0    1.0    1.0    1.0   NaN
     2                 NaN    19.0    36.0    2.0    NaN    1.0    NaN   NaN
     3                 NaN    18.0    37.0    5.0    NaN    NaN    NaN   1.0
     4                 NaN    16.0    36.0    5.0    7.0    1.0    NaN   NaN
1995 1                 NaN    20.0    37.0    9.0    NaN    3.0    NaN   1.0
     2                 NaN    21.0    25.0    2.0    3.0    NaN    NaN   NaN
     3                 NaN    19.0    46.0    7.0    2.0    1.0    1.0   NaN
     4                 NaN    18.0    41.0    3.0    2.0    4.0    1.0   1.0
1996 1                 NaN     7.0    29.0    4.0    1.0    NaN    1.0   NaN
     2                 NaN    19.0    35.0    4.0    1.0    3.0    2.0   NaN
     3                 NaN    21.0    34.0    7.0    3.0    2.0    2.0   1.0
     4                 NaN    24.0    24.0    3.0    5.0    3.0    NaN   NaN
1997 1                 NaN    15.0    19.0    4.0    2.0    1.0    3.0   NaN
     2                 NaN    19.0    39.0    4.0    1.0    NaN    NaN   1.0
     3                 NaN    24.0    33.0    4.0    2.0    NaN    1.0   NaN
     4                 NaN    25.0    32.0    2.0    2.0    3.0    1.0   1.0
1998 1                 NaN    26.0    25.0    3.0    2.0    1.0    NaN   NaN
     2                 NaN    15.0    39.0    4.0    3.0    1.0    NaN   NaN
     3                 NaN    20.0    24.0    6.0    NaN    3.0    1.0   NaN
     4                 NaN    24.0    37.0    4.0    3.0    NaN    NaN   NaN
1999 1                 NaN    19.0    26.0    4.0    2.0    3.0    1.0   NaN
     2                 NaN    22.0    40.0    5.0    1.0    1.0    1.0   1.0
     3                 1.0    26.0    41.0    5.0    3.0    1.0    2.0   NaN
     4                 NaN    25.0    29.0    3.0    4.0    2.0    1.0   1.0
2000 1                 NaN    23.0    30.0    3.0    2.0    NaN    2.0   NaN
     2                 NaN    25.0    22.0    7.0    5.0    2.0    1.0   1.0
     3                 NaN    29.0    25.0    7.0    6.0    1.0    4.0   NaN
     4                 NaN    28.0    29.0    5.0    2.0    2.0    NaN   1.0
2001 1                 NaN    30.0    21.0    3.0    6.0    2.0    1.0   1.0
     2                 NaN    39.0    34.0    1.0    6.0    NaN    3.0   1.0
     3                 NaN    36.0    27.0    4.0    6.0    NaN    NaN   NaN
     4                 NaN    22.0    29.0    2.0    3.0    2.0    1.0   NaN
2002 1                 NaN    22.0    25.0    6.0    3.0    NaN    1.0   NaN
     2                 NaN    34.0    26.0    6.0    3.0    2.0    NaN   1.0
     3                 NaN    37.0    20.0    1.0    2.0    2.0    1.0   NaN
     4                 NaN    32.0    24.0    6.0    1.0    2.0    1.0   NaN
2003 1                 NaN    43.0    27.0    3.0    1.0    2.0    1.0   2.0
     2                 NaN    32.0    33.0    4.0    2.0    NaN    NaN   NaN
     3                 NaN    41.0    34.0    7.0    3.0    1.0    NaN   NaN
     4                 NaN    40.0    29.0    5.0    NaN    2.0    2.0   NaN
2004 1                 NaN    30.0    16.0    7.0    4.0    2.0    1.0   NaN
     2                 NaN    48.0    30.0    4.0    3.0    1.0    2.0   2.0
     3                 NaN    47.0    32.0    2.0    2.0    1.0    3.0   NaN
     4                 NaN    43.0    28.0    3.0    2.0    1.0    1.0   1.0
2005 1                 NaN    43.0    30.0    5.0    6.0    NaN    2.0   4.0
     2                 NaN    36.0    38.0    4.0    3.0    5.0    1.0   4.0
     3                 NaN    34.0    32.0    7.0    1.0    4.0    4.0   1.0
     4                 NaN    43.0    29.0    9.0    3.0    4.0    2.0   1.0
2006 1                 NaN    25.0    33.0    4.0    4.0    1.0    3.0   NaN
     2                 NaN    43.0    29.0    6.0    2.0    4.0    1.0   NaN
     3                 NaN    41.0    21.0    4.0    3.0    3.0    5.0   1.0
     4                 NaN    57.0    23.0    9.0    1.0    1.0    NaN   NaN
2007 1                 NaN    45.0    26.0   10.0    2.0    3.0    1.0   1.0
     2                 NaN    34.0    35.0    7.0    5.0    1.0    5.0   NaN
     3                 NaN    47.0    26.0    2.0    3.0    3.0    2.0   NaN
     4                 NaN    45.0    33.0   10.0    2.0    5.0    1.0   NaN
2008 1                 1.0    35.0    28.0   10.0    1.0    1.0    1.0   NaN
     2                 NaN    37.0    26.0    5.0    2.0    NaN    1.0   NaN
     3                 2.0    44.0    28.0    6.0    4.0    NaN    1.0   2.0
     4                 NaN    51.0    16.0    1.0    3.0    2.0    2.0   1.0
2009 1                 NaN    51.0    19.0    5.0    1.0    NaN    1.0   1.0
     2                 NaN    53.0    26.0    5.0    5.0    2.0    2.0   2.0
     3                 NaN    52.0    18.0    6.0    3.0    2.0    NaN   1.0
     4                 NaN    36.0    24.0    3.0    2.0    NaN    NaN   NaN
2010 1                 NaN    46.0    17.0    3.0    3.0    3.0    1.0   1.0
     2                 NaN    52.0    23.0    7.0    2.0    1.0    NaN   1.0
     3                 NaN    53.0    30.0    7.0    5.0    1.0    2.0   1.0
     4                 NaN    55.0    18.0    8.0    5.0    2.0    NaN   NaN
2011 1                 NaN    39.0    20.0    5.0    1.0    1.0    1.0   2.0
     2                 NaN    33.0    20.0    4.0    2.0    2.0    1.0   1.0
     3                 NaN    49.0    17.0    3.0    4.0    1.0    1.0   2.0
     4                 1.0    50.0    21.0    3.0    NaN    1.0    NaN   NaN
2012 1                 NaN    43.0    12.0    5.0    2.0    1.0    1.0   NaN
     2                 NaN    46.0    12.0    4.0    2.0    2.0    1.0   NaN
     3                 NaN    26.0    11.0   10.0    4.0    1.0    2.0   2.0
     4                 1.0    37.0    19.0    5.0    3.0    NaN    NaN   NaN
2013 1                 1.0    29.0    18.0    3.0    1.0    4.0    2.0   NaN
     2                 NaN    50.0    19.0   12.0    6.0    1.0    2.0   2.0
     3                 NaN    39.0    14.0    5.0    4.0    3.0    1.0   NaN
     4                 NaN    42.0    20.0    6.0    4.0    2.0    NaN   1.0
2014 1                 1.0    36.0    11.0    7.0    1.0    2.0    1.0   3.0
     2                 NaN    41.0    23.0    6.0    1.0    1.0    3.0   2.0
     3                 NaN    42.0    20.0   10.0    4.0    3.0    2.0   2.0
     4                 NaN    42.0    24.0   10.0    4.0    3.0    NaN   1.0
2015 1                 1.0    40.0    17.0    7.0    6.0    4.0    NaN   1.0
     2                 NaN    32.0    18.0    7.0    1.0    1.0    1.0   3.0
     3                 NaN    39.0    18.0    2.0    3.0    1.0    1.0   NaN
     4                 NaN    47.0    18.0   11.0    4.0    2.0    2.0   NaN
2016 1                 NaN    36.0    21.0    5.0    2.0    NaN    1.0   NaN
     2                 NaN    37.0    16.0    4.0    2.0    1.0    NaN   1.0
     3                 NaN    29.0    11.0    6.0    6.0    2.0    NaN   1.0
     4                 NaN    50.0    14.0    4.0    3.0    3.0    NaN   1.0
2017 1                 NaN    40.0     8.0    6.0    1.0    3.0    NaN   1.0
     2                 NaN    41.0    10.0    6.0    2.0    1.0    3.0   NaN
     3                 NaN    35.0    18.0    4.0    3.0    1.0    1.0   NaN
     4                 NaN    42.0    15.0    4.0    1.0    NaN    1.0   NaN
2018 1                 2.0    47.0    14.0    7.0    2.0    1.0    1.0   NaN
     2                 1.0    50.0    11.0    8.0    4.0    3.0    NaN   NaN
     3                 NaN    54.0    13.0    5.0    2.0    2.0    NaN   2.0
     4                 NaN    48.0    15.0    2.0    2.0    1.0    4.0   NaN
2019 1                 NaN    52.0    19.0    6.0    1.0    4.0    NaN   1.0
     2                 1.0    57.0    20.0    9.0    5.0    3.0    3.0   2.0
     3                 NaN    44.0    17.0    3.0    5.0    1.0    2.0   2.0
     4                 NaN    49.0    25.0    7.0    5.0    1.0    1.0   NaN
2020 1                 NaN    50.0    16.0    2.0    3.0    1.0    2.0   1.0
All                   13.0  4131.0  3519.0  655.0  327.0  195.0  136.0  80.0

DepartureDelayGroups   6.0   7.0   8.0   9.0  10.0  11.0  12.0   All
Year Quarter
1987 4                 NaN   NaN   NaN   NaN   NaN   NaN   NaN    52
1988 1                 1.0   1.0   NaN   NaN   NaN   NaN   NaN    63
     2                 NaN   NaN   NaN   NaN   1.0   1.0   NaN    62
     3                 NaN   NaN   NaN   NaN   NaN   NaN   NaN    65
     4                 NaN   NaN   NaN   NaN   NaN   NaN   NaN    64
1989 1                 NaN   NaN   NaN   NaN   NaN   NaN   NaN    64
     2                 NaN   NaN   NaN   NaN   NaN   NaN   NaN    55
     3                 NaN   NaN   NaN   NaN   NaN   NaN   NaN    63
     4                 NaN   NaN   NaN   NaN   NaN   NaN   NaN    48
1990 1                 NaN   NaN   NaN   NaN   NaN   NaN   NaN    57
     2                 NaN   1.0   NaN   NaN   NaN   NaN   NaN    64
     3                 NaN   NaN   NaN   NaN   NaN   NaN   NaN    58
     4                 NaN   NaN   1.0   NaN   NaN   NaN   NaN    63
1991 1                 NaN   NaN   NaN   NaN   NaN   NaN   NaN    50
     2                 NaN   1.0   NaN   NaN   NaN   NaN   NaN    65
     3                 NaN   NaN   NaN   NaN   NaN   NaN   NaN    83
     4                 NaN   NaN   NaN   NaN   NaN   NaN   NaN    55
1992 1                 NaN   NaN   NaN   NaN   NaN   NaN   NaN    54
     2                 NaN   NaN   NaN   NaN   NaN   NaN   NaN    50
     3                 NaN   NaN   NaN   NaN   NaN   NaN   NaN    59
     4                 NaN   NaN   NaN   NaN   1.0   NaN   NaN    71
1993 1                 1.0   NaN   NaN   NaN   NaN   NaN   NaN    56
     2                 NaN   NaN   NaN   NaN   NaN   NaN   1.0    59
     3                 NaN   NaN   NaN   NaN   NaN   NaN   NaN    62
     4                 NaN   NaN   NaN   NaN   NaN   NaN   NaN    49
1994 1                 NaN   NaN   NaN   NaN   NaN   NaN   NaN    54
     2                 NaN   NaN   NaN   NaN   NaN   NaN   NaN    58
     3                 NaN   NaN   NaN   NaN   NaN   NaN   NaN    61
     4                 NaN   NaN   NaN   NaN   NaN   NaN   NaN    65
1995 1                 NaN   1.0   NaN   NaN   NaN   NaN   NaN    71
     2                 NaN   NaN   NaN   NaN   NaN   NaN   NaN    51
     3                 NaN   1.0   NaN   NaN   NaN   NaN   NaN    77
     4                 NaN   NaN   NaN   NaN   NaN   NaN   NaN    70
1996 1                 NaN   NaN   NaN   NaN   1.0   NaN   NaN    43
     2                 NaN   NaN   NaN   NaN   NaN   NaN   NaN    64
     3                 1.0   NaN   NaN   NaN   NaN   NaN   2.0    73
     4                 NaN   NaN   NaN   1.0   NaN   1.0   NaN    61
1997 1                 NaN   2.0   NaN   NaN   NaN   NaN   NaN    46
     2                 NaN   NaN   NaN   NaN   NaN   NaN   1.0    65
     3                 NaN   NaN   NaN   NaN   NaN   1.0   NaN    65
     4                 1.0   NaN   NaN   NaN   1.0   NaN   NaN    68
1998 1                 1.0   NaN   NaN   NaN   NaN   NaN   NaN    58
     2                 1.0   NaN   1.0   NaN   NaN   NaN   NaN    64
     3                 NaN   NaN   1.0   NaN   NaN   NaN   NaN    55
     4                 NaN   NaN   NaN   NaN   NaN   NaN   NaN    68
1999 1                 NaN   NaN   NaN   NaN   NaN   1.0   NaN    56
     2                 NaN   NaN   NaN   NaN   NaN   NaN   NaN    71
     3                 NaN   1.0   NaN   NaN   NaN   NaN   1.0    81
     4                 NaN   NaN   NaN   NaN   NaN   NaN   NaN    65
2000 1                 NaN   1.0   NaN   1.0   NaN   NaN   2.0    64
     2                 NaN   NaN   NaN   NaN   NaN   NaN   2.0    65
     3                 NaN   NaN   NaN   NaN   NaN   NaN   NaN    72
     4                 NaN   NaN   NaN   1.0   NaN   1.0   NaN    69
2001 1                 NaN   1.0   NaN   1.0   NaN   NaN   NaN    66
     2                 1.0   NaN   NaN   NaN   NaN   1.0   NaN    86
     3                 NaN   NaN   NaN   NaN   NaN   NaN   1.0    74
     4                 NaN   NaN   NaN   NaN   1.0   NaN   NaN    60
2002 1                 NaN   NaN   NaN   NaN   NaN   NaN   1.0    58
     2                 1.0   NaN   NaN   1.0   NaN   NaN   NaN    74
     3                 NaN   NaN   NaN   NaN   NaN   NaN   NaN    63
     4                 NaN   NaN   NaN   NaN   NaN   NaN   NaN    66
2003 1                 NaN   NaN   1.0   1.0   NaN   NaN   NaN    81
     2                 NaN   NaN   NaN   NaN   NaN   NaN   NaN    71
     3                 NaN   NaN   NaN   NaN   NaN   NaN   NaN    86
     4                 NaN   1.0   NaN   1.0   NaN   NaN   NaN    80
2004 1                 NaN   NaN   NaN   NaN   NaN   NaN   NaN    60
     2                 1.0   NaN   1.0   1.0   2.0   NaN   NaN    95
     3                 NaN   1.0   NaN   NaN   NaN   NaN   NaN    88
     4                 1.0   NaN   NaN   NaN   NaN   NaN   1.0    81
2005 1                 NaN   NaN   NaN   NaN   NaN   NaN   2.0    92
     2                 NaN   NaN   NaN   NaN   NaN   NaN   NaN    91
     3                 NaN   NaN   NaN   NaN   1.0   NaN   NaN    84
     4                 1.0   NaN   1.0   NaN   NaN   NaN   1.0    94
2006 1                 NaN   1.0   1.0   1.0   NaN   NaN   NaN    73
     2                 1.0   NaN   NaN   NaN   NaN   NaN   NaN    86
     3                 1.0   NaN   NaN   1.0   NaN   NaN   1.0    81
     4                 1.0   NaN   NaN   NaN   2.0   NaN   1.0    95
2007 1                 1.0   NaN   NaN   NaN   1.0   NaN   NaN    90
     2                 NaN   NaN   NaN   1.0   NaN   NaN   NaN    88
     3                 2.0   1.0   3.0   NaN   NaN   NaN   2.0    91
     4                 2.0   NaN   1.0   NaN   2.0   1.0   NaN   102
2008 1                 1.0   2.0   2.0   NaN   1.0   NaN   1.0    84
     2                 2.0   NaN   NaN   NaN   NaN   NaN   NaN    73
     3                 2.0   NaN   NaN   1.0   NaN   1.0   2.0    93
     4                 1.0   NaN   NaN   NaN   NaN   NaN   NaN    77
2009 1                 3.0   1.0   NaN   NaN   NaN   NaN   1.0    83
     2                 1.0   1.0   NaN   NaN   1.0   NaN   NaN    98
     3                 3.0   1.0   NaN   NaN   NaN   NaN   1.0    87
     4                 NaN   NaN   NaN   NaN   NaN   1.0   NaN    66
2010 1                 1.0   NaN   NaN   NaN   1.0   NaN   3.0    79
     2                 NaN   1.0   NaN   NaN   NaN   NaN   1.0    88
     3                 1.0   1.0   NaN   NaN   NaN   NaN   NaN   101
     4                 1.0   NaN   1.0   NaN   NaN   NaN   NaN    90
2011 1                 NaN   2.0   NaN   NaN   1.0   1.0   NaN    73
     2                 1.0   1.0   NaN   NaN   NaN   NaN   1.0    66
     3                 NaN   1.0   NaN   NaN   2.0   NaN   NaN    80
     4                 NaN   1.0   NaN   1.0   NaN   NaN   NaN    78
2012 1                 NaN   1.0   NaN   NaN   NaN   NaN   1.0    66
     2                 1.0   NaN   NaN   NaN   NaN   NaN   NaN    68
     3                 NaN   NaN   2.0   NaN   NaN   NaN   1.0    59
     4                 NaN   NaN   1.0   NaN   NaN   1.0   1.0    68
2013 1                 1.0   NaN   1.0   NaN   NaN   NaN   1.0    61
     2                 NaN   NaN   NaN   1.0   NaN   NaN   NaN    93
     3                 NaN   NaN   NaN   NaN   1.0   NaN   NaN    67
     4                 NaN   1.0   NaN   NaN   NaN   NaN   NaN    76
2014 1                 NaN   1.0   NaN   NaN   NaN   NaN   1.0    64
     2                 1.0   NaN   1.0   NaN   NaN   NaN   1.0    80
     3                 1.0   1.0   NaN   1.0   NaN   NaN   NaN    86
     4                 2.0   2.0   NaN   NaN   NaN   NaN   NaN    88
2015 1                 NaN   1.0   NaN   NaN   1.0   NaN   1.0    79
     2                 NaN   1.0   1.0   1.0   NaN   NaN   1.0    67
     3                 NaN   1.0   NaN   NaN   NaN   NaN   NaN    65
     4                 1.0   1.0   NaN   NaN   NaN   NaN   NaN    86
2016 1                 NaN   NaN   2.0   NaN   NaN   1.0   NaN    68
     2                 2.0   NaN   NaN   NaN   NaN   NaN   NaN    63
     3                 NaN   2.0   1.0   NaN   NaN   NaN   NaN    58
     4                 1.0   NaN   NaN   NaN   NaN   NaN   1.0    77
2017 1                 2.0   NaN   NaN   NaN   NaN   NaN   1.0    62
     2                 1.0   NaN   NaN   1.0   1.0   NaN   2.0    68
     3                 NaN   NaN   NaN   NaN   NaN   NaN   NaN    62
     4                 2.0   NaN   NaN   NaN   1.0   1.0   1.0    68
2018 1                 1.0   NaN   1.0   1.0   NaN   NaN   1.0    78
     2                 NaN   NaN   NaN   1.0   NaN   NaN   NaN    78
     3                 2.0   2.0   1.0   1.0   NaN   1.0   NaN    85
     4                 NaN   1.0   NaN   NaN   NaN   NaN   1.0    74
2019 1                 NaN   NaN   NaN   NaN   NaN   NaN   NaN    83
     2                 1.0   1.0   1.0   NaN   1.0   NaN   NaN   104
     3                 1.0   NaN   NaN   NaN   NaN   NaN   2.0    77
     4                 NaN   NaN   NaN   NaN   NaN   NaN   NaN    88
2020 1                 NaN   NaN   NaN   1.0   NaN   NaN   NaN    76
All                   56.0  42.0  26.0  21.0  24.0  14.0  46.0  9285

In [40]:
pd.pivot_table(adf,
               index = ['Year','Quarter'],
               values = 'ArrTime',
               #aggfunc = 'count',
               columns = 'DepartureDelayGroups',
               margins = True,
              )

DepartureDelayGroups         -2.0         -1.0          0.0          1.0  \
Year Quarter
1987 4                        NaN  1603.142857  1433.685714  1244.571429
1988 1                        NaN  1416.555556  1536.023810  1324.833333
     2                        NaN  1396.000000  1443.195122  1381.000000
     3                        NaN  1430.642857  1450.734694  1621.000000
     4                        NaN  1400.285714  1454.739130  1658.666667
1989 1                        NaN  1447.733333  1380.428571  1715.000000
     2                        NaN  1324.700000  1505.842105  1666.000000
     3                        NaN  1475.000000  1568.046512  1746.750000
     4                        NaN  1628.500000  1515.485714  1298.333333
1990 1                        NaN  1586.250000  1475.757576  1522.000000
     2                        NaN  1364.666667  1513.729730  1684.200000
     3                        NaN  1695.058824  1538.277778  1902.000000
     4                        NaN  1338.692308  1547.900000  1380.400000
1991 1                        NaN  1474.055556  1384.958333  1306.333333
     2                        NaN  1296.294118  1473.850000  1650.500000
     3                        NaN  1527.692308  1548.396552  1716.400000
     4                        NaN  1463.142857  1438.918919  1259.000000
1992 1                        NaN  1358.000000  1511.545455  1331.500000
     2                        NaN  1340.533333  1517.531250  1695.333333
     3                        NaN  1473.928571  1430.692308  2106.000000
     4                        NaN  1493.733333  1401.369565  1488.875000
1993 1                        NaN  1180.714286  1544.666667  1737.500000
     2                        NaN  1411.625000  1483.533333  1614.000000
     3                        NaN  1547.454545  1370.285714  2023.333333
     4                        NaN  1486.900000  1471.904762  1789.833333
1994 1                        NaN  1601.200000  1460.333333  1589.000000
     2                        NaN  1522.210526  1378.222222  1556.500000
     3                        NaN  1551.944444  1640.945946  1612.600000
     4                        NaN  1308.562500  1558.972222  1580.400000
1995 1                        NaN  1513.700000  1566.459459  1322.111111
     2                        NaN  1390.571429  1712.080000  1532.500000
     3                        NaN  1573.894737  1486.108696  1638.714286
     4                        NaN  1428.444444  1526.048780  1166.000000
1996 1                        NaN  1515.428571  1362.655172  1465.750000
     2                        NaN  1483.578947  1375.571429  1504.500000
     3                        NaN  1371.476190  1493.294118  1747.571429
     4                        NaN  1435.000000  1574.250000  1427.666667
1997 1                        NaN  1504.266667  1602.684211  1655.500000
     2                        NaN  1488.000000  1562.461538  1542.750000
     3                        NaN  1491.583333  1460.250000  1293.500000
     4                        NaN  1456.160000  1516.718750  1688.500000
1998 1                        NaN  1181.846154  1634.040000   915.666667
     2                        NaN  1367.400000  1317.461538  1982.000000
     3                        NaN  1530.750000  1499.875000  1849.500000
     4                        NaN  1584.000000  1441.378378  1647.750000
1999 1                        NaN  1498.263158  1606.500000  1896.000000
     2                        NaN  1413.136364  1506.950000  1532.000000
     3                  16.000000  1583.307692  1515.000000  1146.200000
     4                        NaN  1426.400000  1385.724138  1741.000000
2000 1                        NaN  1582.782609  1526.133333  1892.000000
     2                        NaN  1460.520000  1631.727273  1692.000000
     3                        NaN  1285.689655  1547.720000  1267.285714
     4                        NaN  1522.035714  1286.241379  1779.400000
2001 1                        NaN  1454.466667  1543.809524  1436.666667
     2                        NaN  1428.358974  1407.970588  1859.000000
     3                        NaN  1510.138889  1584.518519  1761.500000
     4                        NaN  1384.636364  1499.241379  1857.500000
2002 1                        NaN  1501.954545  1588.640000  1431.000000
     2                        NaN  1449.970588  1472.692308  1790.166667
     3                        NaN  1596.405405  1467.800000  1936.000000
     4                        NaN  1427.906250  1605.250000  1643.666667
2003 1                        NaN  1447.418605  1429.185185  1717.666667
     2                        NaN  1435.750000  1680.181818  1737.750000
     3                        NaN  1513.926829  1547.676471  1626.571429
     4                        NaN  1324.675000  1614.896552  1834.000000
2004 1                        NaN  1542.133333  1440.733333  1694.714286
     2                        NaN  1362.937500  1407.866667  1575.000000
     3                        NaN  1394.595745  1545.031250  1622.500000
     4                        NaN  1336.186047  1399.285714  1359.000000
2005 1                        NaN  1541.309524  1345.433333  2009.000000
     2                        NaN  1428.333333  1576.210526  1235.750000
     3                        NaN  1357.676471  1436.937500  1857.285714
     4                        NaN  1460.837209  1513.931034  1416.000000
2006 1                        NaN  1237.560000  1352.937500  1579.000000
     2                        NaN  1466.069767  1573.068966  1508.333333
     3                        NaN  1365.634146  1582.761905  1430.000000
     4                        NaN  1299.105263  1339.521739  1580.222222
2007 1                        NaN  1373.533333  1550.615385  1624.700000
     2                        NaN  1292.529412  1493.285714  1744.000000
     3                        NaN  1417.829787  1413.884615  1608.000000
     4                        NaN  1412.777778  1609.656250  1852.800000
2008 1                 846.000000  1496.142857  1524.464286  1425.600000
     2                        NaN  1470.351351  1583.730769  1961.000000
     3                2065.000000  1489.772727  1457.178571  1596.166667
     4                        NaN  1454.803922  1458.750000  1446.000000
2009 1                        NaN  1536.137255  1590.315789  1481.600000
     2                        NaN  1371.924528  1659.269231  1514.800000
     3                        NaN  1319.519231  1589.166667  1524.000000
     4                        NaN  1466.611111  1555.708333  1485.666667
2010 1                        NaN  1320.934783  1319.764706  1926.333333
     2                        NaN  1429.365385  1579.434783  1884.428571
     3                        NaN  1453.811321  1626.800000  1538.000000
     4                        NaN  1490.527273  1468.111111  1676.000000
2011 1                        NaN  1498.282051  1364.100000  2030.000000
     2                        NaN  1362.727273  1524.900000  1904.250000
     3                        NaN  1401.367347  1562.529412  1392.000000
     4                 445.000000  1482.400000  1566.142857  1975.000000
2012 1                        NaN  1532.465116  1471.000000  1761.600000
     2                        NaN  1387.260870  1667.833333  1296.500000
     3                        NaN  1416.115385  1597.000000  1537.600000
     4                 835.000000  1516.405405  1674.631579  1977.200000
2013 1                1401.000000  1463.793103  1356.611111  1732.666667
     2                        NaN  1452.840000  1611.000000  1456.500000
     3                        NaN  1431.871795  1555.785714  1520.400000
     4                        NaN  1430.000000  1575.900000  1797.833333
2014 1                2243.000000  1452.972222  1703.272727  1569.000000
     2                        NaN  1412.780488  1499.000000  2009.833333
     3                        NaN  1458.523810  1504.950000  1804.900000
     4                        NaN  1462.333333  1554.791667  1436.900000
2015 1                1109.000000  1314.750000  1584.823529  1463.714286
     2                        NaN  1363.093750  1477.611111  1894.857143
     3                        NaN  1370.307692  1445.555556  1893.500000
     4                        NaN  1438.510638  1446.722222  1775.400000
2016 1                        NaN  1394.555556  1389.476190  1323.600000
     2                        NaN  1469.702703  1594.562500  1517.750000
     3                        NaN  1317.068966  1630.090909  1749.166667
     4                        NaN  1404.480000  1519.071429  1736.500000
2017 1                        NaN  1391.875000  1572.000000  1795.000000
     2                        NaN  1270.609756  1182.500000  1778.666667
     3                        NaN  1389.742857  1464.588235  1884.750000
     4                        NaN  1524.833333  1568.600000  1566.250000
2018 1                1836.000000  1430.595745  1593.714286  1615.428571
     2                1417.000000  1365.360000  1650.181818  1263.375000
     3                        NaN  1505.888889  1467.076923  1362.400000
     4                        NaN  1274.583333  1418.333333  2048.500000
2019 1                        NaN  1400.769231  1560.210526  1389.166667
     2                 805.000000  1418.280702  1461.600000  1523.777778
     3                        NaN  1347.204545  1711.235294  1400.666667
     4                        NaN  1411.673469  1474.583333  1500.857143
2020 1                        NaN  1493.820000  1804.437500  1146.000000
All                   1301.461538  1429.602906  1503.824936  1610.523737

DepartureDelayGroups          2.0          3.0          4.0          5.0  \
Year Quarter
1987 4                2307.000000  1780.000000          NaN          NaN
1988 1                        NaN  1294.500000  1821.000000  1850.000000
     2                1738.333333  1929.000000          NaN   130.000000
     3                 117.000000          NaN          NaN          NaN
     4                1671.000000          NaN  1320.000000  1618.000000
1989 1                1767.000000  1642.500000  1212.500000          NaN
     2                1637.000000          NaN          NaN  1851.000000
     3                1730.000000          NaN  1115.000000  2135.000000
     4                2306.000000  1937.000000          NaN          NaN
1990 1                        NaN          NaN  2219.000000          NaN
     2                        NaN          NaN          NaN          NaN
     3                        NaN  2224.000000  1969.000000          NaN
     4                1974.333333          NaN  1337.000000          NaN
1991 1                1950.000000    27.000000          NaN          NaN
     2                2225.000000          NaN          NaN          NaN
     3                1240.500000  1926.000000          NaN  1011.000000
     4                1701.000000          NaN  1153.000000          NaN
1992 1                2207.000000  1138.000000          NaN          NaN
     2                        NaN          NaN          NaN          NaN
     3                2018.333333  2303.000000          NaN          NaN
     4                        NaN  2052.000000          NaN          NaN
1993 1                1909.666667  1848.000000  2342.000000          NaN
     2                1505.000000  1537.000000          NaN          NaN
     3                1815.000000  2247.000000          NaN          NaN
     4                2224.000000  1606.000000          NaN          NaN
1994 1                1334.000000  1936.000000  1838.000000          NaN
     2                        NaN  1929.000000          NaN          NaN
     3                        NaN          NaN          NaN  2251.000000
     4                1744.428571  1110.000000          NaN          NaN
1995 1                        NaN  1766.000000          NaN  1359.000000
     2                1765.000000          NaN          NaN          NaN
     3                1924.000000  1000.000000  1859.000000          NaN
     4                1839.000000  1685.000000  2233.000000  2234.000000
1996 1                1341.000000          NaN  1847.000000          NaN
     2                1406.000000  2086.000000   962.000000          NaN
     3                1572.333333  2133.500000  1550.500000  2108.000000
     4                1622.800000  1805.000000          NaN          NaN
1997 1                1814.500000  2217.000000  1782.333333          NaN
     2                2040.000000          NaN          NaN   223.000000
     3                1575.000000          NaN  1453.000000          NaN
     4                1381.000000  1692.000000  1901.000000  2331.000000
1998 1                2277.500000  2242.000000          NaN          NaN
     2                1412.666667  1743.000000          NaN          NaN
     3                        NaN  1391.000000  1540.000000          NaN
     4                1520.333333          NaN          NaN          NaN
1999 1                1581.000000  1800.666667  2223.000000          NaN
     2                  34.000000    10.000000   204.000000   107.000000
     3                1565.666667  1716.000000  1629.500000          NaN
     4                1812.000000  1633.500000  1454.000000  2259.000000
2000 1                1767.500000          NaN  2032.000000          NaN
     2                1504.000000  1463.000000  2304.000000  2232.000000
     3                1608.500000  1548.000000  1769.250000          NaN
     4                1594.000000  1785.500000          NaN  1537.000000
2001 1                1671.000000  1100.000000  1351.000000  2000.000000
     2                1866.166667          NaN  1945.333333  1218.000000
     3                1953.833333          NaN          NaN          NaN
     4                1265.000000  1528.000000  1835.000000          NaN
2002 1                2006.333333          NaN  2123.000000          NaN
     2                1547.000000  2069.500000          NaN  2047.000000
     3                2035.500000   820.500000  1426.000000          NaN
     4                1650.000000   791.500000  1329.000000          NaN
2003 1                2229.000000  2184.500000  1655.000000  1077.500000
     2                2148.000000          NaN          NaN          NaN
     3                1860.000000   622.000000          NaN          NaN
     4                        NaN  1213.500000  1518.500000          NaN
2004 1                1663.250000  1427.000000  2114.000000          NaN
     2                1435.666667  2133.000000  1324.500000  1791.000000
     3                1731.000000  1656.000000  1636.333333          NaN
     4                1291.000000  1249.000000  2234.000000  2235.000000
2005 1                1527.666667          NaN  1481.000000  1967.000000
     2                1705.666667  1631.000000  1759.000000  1372.750000
     3                2300.000000  1081.000000  1408.250000   840.000000
     4                1600.000000  1858.750000  1633.500000  2019.000000
2006 1                1446.000000  2017.000000  2158.666667          NaN
     2                1928.500000  1777.750000    56.000000          NaN
     3                1685.000000  1061.000000  1967.400000  2350.000000
     4                1408.000000  1849.000000          NaN          NaN
2007 1                1841.500000  1663.666667  1730.000000  1930.000000
     2                2090.400000  1250.000000  2108.400000          NaN
     3                1103.666667  1762.333333  1477.000000          NaN
     4                1382.500000  1813.600000  1155.000000          NaN
2008 1                2234.000000  1900.000000  1554.000000          NaN
     2                1686.000000          NaN  1158.000000          NaN
     3                1846.750000          NaN  1630.000000  1715.000000
     4                2066.000000  1634.000000  1584.000000  1259.000000
2009 1                1603.000000          NaN  2050.000000  2400.000000
     2                1789.200000  1623.500000  1386.000000  1944.000000
     3                1720.666667  1119.500000          NaN  1858.000000
     4                1549.000000          NaN          NaN          NaN
2010 1                1444.333333  1263.666667  1701.000000  1202.000000
     2                 876.500000  1659.000000          NaN  2244.000000
     3                1692.400000  2224.000000  1766.500000    58.000000
     4                1792.600000  1506.500000          NaN          NaN
2011 1                1312.000000  2058.000000  1417.000000  1805.500000
     2                 492.000000  1832.500000  2341.000000  2311.000000
     3                1832.000000  1525.000000  2020.000000  1796.000000
     4                        NaN  1548.000000          NaN          NaN
2012 1                1795.500000   613.000000  2149.000000          NaN
     2                1893.500000  1233.500000  1902.000000          NaN
     3                1613.750000  1437.000000    20.000000  2137.500000
     4                1390.000000          NaN          NaN          NaN
2013 1                1734.000000  1568.250000  1700.500000          NaN
     2                1556.000000  1934.000000  1677.500000  1700.000000
     3                1711.750000  2001.000000  1414.000000          NaN
     4                1346.500000   327.500000          NaN  1917.000000
2014 1                1327.000000  1964.500000  2154.000000   693.333333
     2                1755.000000  2347.000000  1550.333333    93.000000
     3                1782.500000  1654.000000  1722.500000   679.000000
     4                1932.500000  1710.333333          NaN  1341.000000
2015 1                1932.166667  1761.500000          NaN  1612.000000
     2                2122.000000    56.000000  1644.000000  1263.333333
     3                1717.666667  1458.000000  1850.000000          NaN
     4                1264.500000  1042.000000  1532.500000          NaN
2016 1                1741.500000          NaN  2347.000000          NaN
     2                1227.000000   849.000000          NaN  1919.000000
     3                1725.000000  1035.000000          NaN  2104.000000
     4                1821.666667  1749.000000          NaN  1333.000000
2017 1                2026.000000  1603.666667          NaN  1308.000000
     2                 920.500000  1814.000000  1541.333333          NaN
     3                1918.666667  1313.000000  1050.000000          NaN
     4                2303.000000          NaN    23.000000          NaN
2018 1                1839.500000  2144.000000  1920.000000          NaN
     2                1181.500000  1972.000000          NaN          NaN
     3                1912.000000   774.500000          NaN  1814.000000
     4                1730.000000  1457.000000  1425.750000          NaN
2019 1                2313.000000  1759.000000          NaN  1241.000000
     2                1859.200000   350.333333  1699.000000  1679.500000
     3                1543.800000  1757.000000  1689.000000  2129.000000
     4                1465.800000  1935.000000  1408.000000          NaN
2020 1                 666.000000  1628.000000  1974.000000  1612.000000
All                   1670.769939  1575.615385  1634.625000  1569.312500

DepartureDelayGroups          6.0          7.0          8.0          9.0  \
Year Quarter
1987 4                        NaN          NaN          NaN          NaN
1988 1                2246.000000  1337.000000          NaN          NaN
     2                        NaN          NaN          NaN          NaN
     3                        NaN          NaN          NaN          NaN
     4                        NaN          NaN          NaN          NaN
1989 1                        NaN          NaN          NaN          NaN
     2                        NaN          NaN          NaN          NaN
     3                        NaN          NaN          NaN          NaN